### ISSUE TITLE
[Request] To support for latest React Native & Appwrite

### ISSUE THREAD

**Issue by anirudhuuu** [DiegoBM/react-native-appwrite-oauth#2]
Hi there,

The current package doesn't allow to get installed for the following version of react native and app-write. Any plans in upgrading to latest version?

```
"appwrite": "^11.0.0",
"react": "18.2.0",
"react-native": "0.71.8",
```

Thanks for your support!

**Comment by DiegoBM** [comment]
Apologies, I was using very restrictive versions for the peer dependencies. It should install without issues now.
